import type { NextPage } from "next";
import Head from "next/head";

import { ShoppingCartSimple } from "phosphor-react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>One Product Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col md:flex-row flex-grow">
        <div className="w-full h-full flex items-center justify-center md:bg-gray-200 pt-5 md:pt-0">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="img/2.png"
            alt=""
            className="w-auto max-w-xl object-contain max-h-[60vh] md:w-full"
          />
        </div>
        <div className="w-full h-full flex flex-col items-center pt-10 md:pt-20">
          <h1 className="text-4xl font-title">IPhone 14 Pro</h1>
          <h2 className="text-xl text-gray-500">256GB, Space Gray</h2>

          <h2 className="text-3xl font-title my-5 md:my-10">999 $</h2>

          <h4 className="mb-4 text-gray-500">Free shipping to EU countries</h4>
          <button className="flex items-center gap-2 p-4 bg-red-500 rounded-lg text-white hover:bg-red-600 mb-20 md:mb-0">
            Add to cart <ShoppingCartSimple size={16} weight="bold" />
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
