import type { NextPage } from "next";
import Head from "next/head";

import Image from "next/future/image";

import { ShoppingCartSimple } from "phosphor-react";
import { useEffect } from "react";
import { useCartContext } from "../context/CartContext";

const product = {
  id: "prod_MPn2hytSZWer68",
  active: true,
  description: "Very kox phone",
  images: [
    "https://files.stripe.com/links/MDB8YWNjdF8xSzk3Vk1McE9ySGZxYzZHfGZsX3Rlc3RfSEQ1VnVDTGRxODlkclVoblNRajlpZWlY005onTxPIM",
  ],
  name: "IPhone 14 Pro Max",
  price: 5,
};

const Home: NextPage = () => {
  const { increaseCartQuantity, cartQuantity } = useCartContext();

  useEffect(() => {
    console.log(cartQuantity);
  }, [cartQuantity]);
  return (
    <>
      <Head>
        <title>One Product Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col md:flex-row flex-grow">
        <div className="w-full h-full flex items-center justify-center md:bg-gray-200 pt-5 md:pt-0">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="img/2.png"
            alt=""
            className="w-auto max-w-xl object-contain max-h-[60vh] md:w-full"
          />
        </div>
        <div className="w-full h-full flex flex-col items-center pt-10 md:pt-20">
          <h1 className="text-4xl font-title">IPhone 14 Pro</h1>
          <h2 className="text-xl text-gray-500">256GB, Space Gray</h2>

          <h2 className="text-3xl font-title my-5 md:my-10">$ 999</h2>

          <h4 className="mb-4 text-gray-500 text-sm italic">
            Free shipping to EU countries.
          </h4>
          <button
            className="select-none flex items-center gap-2 p-4 bg-red-500 rounded-lg text-white hover:bg-red-600 mb-20 md:mb-0"
            onClick={() => increaseCartQuantity(product)}
          >
            Add to cart <ShoppingCartSimple size={16} weight="bold" />
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
